# Generated by Django 5.2 on 2025-05-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak_performance', '0003_calllog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
