# Generated by Django 5.2 on 2025-07-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_performance', '0005_alter_project_name_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='id',
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='callback_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='log_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='requires_callback',
            field=models.BooleanField(default=False),
        ),
    ]
